name: Python app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Synk 
      run: npm install -g snyk
      
    - name: Snyk test for finding vulnerabilities
      continue-on-error: true
      run: synk test 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

